# Generated by Django 5.1.4 on 2025-01-24 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_remove_payment_booking_service_availability_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(default="other", max_length=50),
        ),
        migrations.AddField(
            model_name="service",
            name="duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="max_clients_per_slot",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="service",
            name="predicted_category",
            field=models.CharField(
                blank=True,
                help_text="Category suggested by AI (can be overridden manually).",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="terms_and_conditions",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ServiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_required", models.BooleanField(default=False)),
                ("max_selections", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="service.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOptionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "additional_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="service.serviceoption",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BlockedTime",
        ),
    ]
