# Generated by Django 5.1.4 on 2025-01-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_service_category_service_duration_minutes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="terms_and_conditions",
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="location",
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="predicted_category",
            field=models.CharField(
                blank=True,
                default=1,
                help_text="Category suggested by AI (can be overridden manually).",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
